# Generated by Django 5.0.2 on 2024-03-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0003_alter_report_user_email_alter_report_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to='images'),
        ),
    ]
