# Generated by Django 5.0.3 on 2024-03-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0004_alter_report_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_file',
        ),
        migrations.AddField(
            model_name='report',
            name='report_file_name',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='images')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistleblower.report')),
            ],
        ),
    ]
