# Generated by Django 5.0.2 on 2024-03-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0005_remove_report_report_file_report_report_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='report_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
