# Generated by Django 5.0.2 on 2024-03-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0006_alter_reportfile_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.TextField(default='NOT PROVIDED'),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default='NOT PROVIDED'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TextField(default='NOT PROVIDED'),
        ),
    ]
