# Generated by Django 5.0.2 on 2024-04-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0007_report_admin_notes_report_date_report_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default='NOT PROVIDED'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default='NOT PROVIDED'),
        ),
    ]
